// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieiuhojoaoawofyzgxiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllaXVob2pvYW9hd29meXpneGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODk0NzIsImV4cCI6MjA3MDE2NTQ3Mn0.cTfZzgNhauoQyvV_gRCf6LcXE0eQX_FttaXEkZurZ7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});